spring:
  application:
    name: async-service
  data:
    mongodb:
      uri: mongodb://${MONGODB_USER:mongodb}:${MONGODB_PASSWORD:mongodb}@${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/${MONGODB_DATABASE:telecomdb}?authSource=admin
server:
  port: ${SERVER_PORT:8080}
point:
  retry:
    interval: ${RETRY_INTERVAL:30000}  # 30초마다 재시도
    max-count: ${RETRY_MAX_COUNT:3}    # 최대 재시도 횟수

services:
  point:
    url: ${POINT_SERVICE_URL:http://point}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
    doc-expansion: none
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json