apiVersion: apps/v1
kind: Deployment
metadata:
  name: point-mart
  namespace: dg0100-resilience-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: point-mart
  template:
    metadata:
      labels:
        app: point-mart
    spec:
      containers:
      - name: point-mart
        image: dg0100cr.azurecr.io/membership/point:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: point-mart
        - secretRef:
            name: postgres-point
        resources:
          requests:
            cpu: 256m
            memory: 256Mi
          limits:
            cpu: 512m
            memory: 512Mi
