spring:
  application:
    name: point-service
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:membershipdb}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    pool:
      initial-size: 10
      max-size: 50
      max-idle-time: 30m
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

server:
  port: ${SERVER_PORT:8080}

azure:
  eventgrid:
    endpoint: ${EVENTGRID_ENDPOINT}
    key: ${EVENTGRID_KEY}
    topic: ${EVENTGRID_TOPIC}

# Swagger UI 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
    doc-expansion: none
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
