apiVersion: v1
kind: Service
metadata:
  name: async
  namespace: dg0100-resilience-ns

spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8082
  selector:
    app: async
  sessionAffinity: None
  type: LoadBalancer